"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
# 운영체제에 가까움. 앱을 실행할 때 그 즉시 설정을 만져줘야 함.
from dotenv import load_dotenv
from pathlib import Path
import os

load_dotenv()

LOGIN_REDIRECT_URL = "polls:index"   # 로그인 성공 후 polls 홈으로
LOGOUT_REDIRECT_URL = "polls:index"  # 로그아웃 후 polls 홈으로 (원하면)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY") or "ci-dev-secret-key"
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
# 앱을 설치하자마자 해줘야 할 것.
# Django안에 들어가는 것들은 모두 다 여기 선언을 해 줘야함.
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'polls.apps.PollsConfig',
    'django_extensions',
    'debug_toolbar',
    "accounts",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, "templates"],
        #경로
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    "default": {
        # Django가 사용할 데이터베이스 종류
        # sqlite3 → postgresql로 변경됨
        "ENGINE": "django.db.backends.postgresql",

        # 사용할 데이터베이스 이름
        # 환경변수 POSTGRES_DB가 있으면 그 값을 사용
        # 없으면 기본값 "django_first2_db" 사용
        "NAME": os.environ.get("POSTGRES_DB", "django_first2_db"),

        # PostgreSQL 접속 계정 이름
        # 환경변수 POSTGRES_USER가 있으면 그 값을 사용
        # 없으면 기본값 "django_user" 사용
        "USER": os.environ.get("POSTGRES_USER", "django_user"),

        # PostgreSQL 접속 비밀번호
        # 환경변수 POSTGRES_PASSWORD가 있으면 그 값을 사용
        # 없으면 기본값 "strong-password" 사용
        # (실무에서는 기본값 없이 env로만 관리하는 경우가 많음)
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "strong-password"),

        # PostgreSQL 서버 주소
        # 로컬 개발/CI에서는 보통 127.0.0.1 (내 컴퓨터)
        # GitHub Actions service를 쓰는 경우엔 "postgres"가 될 수도 있음
        "HOST": os.environ.get("POSTGRES_HOST", "127.0.0.1"),

        # PostgreSQL 서버 포트
        # 기본 포트는 5432
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
INTERNAL_IPS = [
    "127.0.0.1",
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# 영어로 나오는거 싫다 -> 바로 한글로 나오게 바꾸고
LANGUAGE_CODE = 'ko-kr'

# 시간도 우리나라에 맞게 설정.
TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",   # ✅ 공통 static 폴더
]

# 배포용(지금 당장은 없어도 됨, 하지만 나중에 꼭 필요)
STATIC_ROOT = BASE_DIR / "staticfiles"
